spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/jwt?characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: 123456
  redis:
    host: 192.168.182.135
    port: 6379

mybatis:
  type-aliases-package: com.wzj.domain
  mapper-locations: classpath:mybatis/*.xml
server:
  port: 8888


